export const REQUEST_POSTS = 'REQUEST_POSTS'
export const FETCH_POSTS = 'FETCH_POSTS'
export const SWITCH_FAV = 'SWITCH_FAV'
// export const DELETE_FROM_FAV = 'DELETE_FROM_FAV'
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
export const SWITCH_PAGE = 'SWITCH_PAGE'